language: node_js
os: linux
dist: xenial
node_js:
- '12.13'
jobs:
  include:
  - stage: Run tests
    script: npm test
  - stage: Publish package
    deploy:
      provider: npm
      on:
        branch: master
      email: $EMAIL_ADDRESS
      api_key: $NPM_API_KEY_ENCRYPTED